services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_DB: ${DB_NAME}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/userStore?sslmode=disable
    depends_on:
      - postgres
    command: [ "/app/main" ]